#!/bin/bash

set -e

# Runs the nodejs application server.
run_static_site() {
  echo "Launching static site"

  exec npx serve -s $BUILD_DIR
}

# Allow debugging the builder image itself, by using:
# $ docker run -it bucharestgold/centos-s2i-nodejs --debug
#
[ "$1" == "--debug" ] && exec /bin/bash

run_static_site
